name: Publish

on:
  push:
    branches:
      - main 

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Assemble AAR
        run: |
          echo ${{ secrets.GITHUB_USERNAME }}
          echo ${{ secrets.GITHUB_PAT }}
          sed -i 's/USER_NAME/${{ secrets.GITHUB_USERNAME }}/g' settings.gradle
          sed -i 's/GIT_PAT/${{ secrets.GITHUB_PAT }}/g' settings.gradle
          
      - name: Publish
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/aar/*.aar"
          replacesArtifacts: false
          allowUpdates: true
          tag: ${{needs.release.outputs.tag}}