name: Publish

on:
  push:
    branches:
      - main 

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
env:
  GITHUB_PAT_TOKEN: ${{secrets.GITHUB_PAT_TOKEN}}
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
          
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1


      - name: Assemble AAR
        run: |
          
          ./gradlew assembleRelease -GITHUB_PAT_TOKEN=$GITHUB_PAT_TOKEN

      - name: Assemble AAR
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Publish
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/aar/*.aar"
          replacesArtifacts: false
          allowUpdates: true
          tag: ${{needs.release.outputs.tag}}